### ISSUE TITLE
Globbing in empty directories

### ISSUE THREAD

**Issue by layus** [Boruch-Baum/morc_menu#1]
When a directory is empty, i get the following error and an empty line in the produced dmenu.

morc_menu: ligne 498: /home/layus/.local/share/applications/*.desktop: Aucun fichier ou dossier de ce type
(No such file or directory).

**Comment by Boruch-Baum** [comment]
BUG CONFIRMED and FIXED
Thank you.
The fix is commit 433046898e307be0d81db417629601cae6a309d0
One line after the current #498, to read: [ -r "${in_file}" ] || continue

Your issue brought up other things to my attention also, so thanks much.

**Comment by layus** [comment]
Nice ! I will continue to use this project :-).
